### ISSUE TITLE
How to train dual-PointNetGPD model

### ISSUE THREAD

**Issue by kgmin156** [ymxlzgy/DA2#1]
Thank you for your works with dual arm manipulation

I wonder that how can T train the dual-PointNetGPD suggested in the paper?
there are only scene rendering code....

**Comment by kgmin156** [comment]
also link to download full dataset(especially main files link) is wrong.
Could you check it one more time?
Thank you.

**Comment by ymxlzgy** [comment]
> also link to download full dataset(especially main files link) is wrong. Could you check it one more time? Thank you.

Unfortunately, the uploaded data seems to vanish somehow..... And I recently cleaned my disk for free space...so I also don't have the data from my side.... truly sorry :( But I hope the code can still work. Would you mind running the code first? I am working on the post submission these days, so maybe it's better if you can generate it on your machine. I mean it's not that time-consuming, just need a 16-thread CPU and work for at most 5 days. And don't forget to adjust the thread number in the multiprocessing pool! Let me know if you need any help when reproducing the code!

**Comment by ymxlzgy** [comment]
> Thank you for your works with dual arm manipulation
> 
> I wonder that how can T train the dual-PointNetGPD suggested in the paper? there are only scene rendering code....

Thanks for your interest. It is limited to providing the code due to the policy, but it is really easy to reproduce the performance. After the rendering, you can just modify the dataloader in the original pointnetgpd and follow the instruction on the coordinate transformation in the paper to reproduce it.

**Comment by kgmin156** [comment]
> 

Thank you for reply. I'm trying to reproduce whole dataset generation and there are some problem. 
1. The RAM memory is explode after some iterate progress. I think there are for loop or used mesh data is allocated at the memory which should be deleted after iteration can you check it? 
2. the line 40 in generate_dual_dataset.py, is wrong i think. the grasp data should be saved in objname_scale.h5, but it saved in just _scale.h5. it should be change to 
h5py.File(grasp_dir + OBJ_FILENAME.split('/')[-1].split('.')[0] + '_{}'.format(scale) + '.h5', 'w')
thank you

**Comment by ymxlzgy** [comment]
Thanks for the message. I noticed that bug loop and have fixed it in my recent work, and I will update it. Meanwhile, I am regenerating the whole dataset and I will upload it later and let you know.
Cheers.

**Comment by kgmin156** [comment]
> Thanks for the message. I noticed that bug loop and have fixed it in my recent work, and I will update it. Meanwhile, I am regenerating the whole dataset and I will upload it later and let you know. Cheers.

Thanks for fix the bug and regenerating the whole dataset again.

**Comment by ymxlzgy** [comment]
Hey, just want to let you know I regenerated the dataset and uploaded it to the server. You can access it on the project website. Cheers.
